services:
  app:
    build: 
      context: ../
      dockerfile: docker/Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.will_challenges.rule=Host(`will-challenges.sucss.org`)"
      - "traefik.http.routers.will_challenges.tls=true"
      - "traefik.http.routers.will_challenges.middlewares=authentik@file"
      - "traefik.http.services.will_challenges.loadbalancer.server.port=8000"

    networks:
      - traefik

networks:
  traefik:
    external: true
